### ISSUE TITLE
Proposal: Please start using Semantic Versioning

### ISSUE THREAD

**Issue by KateGo520** [dreadl0ck/ja3#5]
I found that this project already [supports Go modules](https://github.com/dreadl0ck/ja3/blob/master/go.mod). But sadly, the [tags](https://github.com/dreadl0ck/ja3/tags) doesn't follow [Semantic Versioning](https://semver.org), which means that all tags of this project will be ignored by Go modules and replaced by pseudo-versions, go get acts weirdly when tags are not in that form. It would be great to have the tagged release be named in the format vX.X.X format so that go mod can read it. 
```
$go get github.com/dreadl0ck/ja3@v1.0
go get github.com/dreadl0ck/ja3@v1.0: no matching versions for query "v1.0"
$go get github.com/dreadl0ck/ja3
go: downloading github.com/dreadl0ck/ja3 v0.0.0-20200304222813-39f4a089559b
go: github.com/dreadl0ck/ja3 upgrade => v0.0.0-20200304222813-39f4a089559b
```
Else the mod file shows something like `github.com/dreadl0ck/ja3 v0.0.0-20200304222813-39f4a089559b` which is not very readable and difficult to upgrade. It’s hard to verify which version is in use. This is not conducive to version control.

So, I propose this project to follow Semantic Versioning in future versions. For example, `v1.0.1`, `v2.0.0`, `v3.1.0-alpha`, `v3.1.0-beta.2`etc, so that other project can use tag in go.mod.

**Comment by KateGo520** [comment]
@dreadl0ck  Could you help me review this issue? Thx :p

**Comment by dreadl0ck** [comment]
Hi there,

thanks for the heads up, will make a new release :)

**Comment by dreadl0ck** [comment]
There you go: 39f4a08

Let me know if that works for you!

**Comment by KateGo520** [comment]
@dreadl0ck  Yes. It works well now!
```
$go get github.com/dreadl0ck/ja3
go: github.com/dreadl0ck/ja3 upgrade => v1.0.0
go: downloading github.com/dreadl0ck/ja3 v1.0.0
```

**Comment by dreadl0ck** [comment]
Awesome, glad to help!
