### ISSUE TITLE
request for pcap.h

### ISSUE THREAD

**Issue by guillermo-menjivar** [dreadl0ck/ja3#7]
When I try to compile ja3 I am prompted with the following error
```
go build -o $(go env GOPATH)/bin/goja3 -i github.com/dreadl0ck/ja3/cmd
# github.com/google/gopacket/pcap
../test/pkg/mod/github.com/google/gopacket@v1.1.18/pcap/pcap_unix.go:34:18: fatal error: pcap.h: No such file or directory
compilation terminated.
```

**Comment by dreadl0ck** [comment]
The commandline tool imports gopacket's pcap package to be able to attach to a network interface.

You need to install _libpcap_ on your system and ensure the go compiler can find it.

**Comment by guillermo-menjivar** [comment]
Thank you @dreadl0ck
