### ISSUE TITLE
Error on running goja3 on win machine

### ISSUE THREAD

**Issue by tee2015** [dreadl0ck/ja3#8]
>goja3.exe -iface Ethernet0
panic: Loopback: No such device exists (No such device exists)

goroutine 1 [running]:
github.com/dreadl0ck/ja3.ReadInterface(0xc0000100b8, 0x8, 0xcbf000, 0xc000006018, 0xc718f6, 0x1, 0xc000070101, 0x5ea, 0xc00003e001, 0xffffffffff676980)
        C:/Users/win/Desktop/ja3-master/live.go:23 +0x26e5
main.main()
        C:/Users/win/Desktop/ja3-master/cmd/main.go:56 +0x34e

**Machine is a VM and have Ethernet0** 

Idx     Met         MTU          State                Name
---  ----------  ----------  ------------  ---------------------------
 **12          25        1500  connected     Ethernet0**

**Comment by dreadl0ck** [comment]
For windows, things work a little bit different, attaching by network interface name is not possible.

First, download & install the latest version of WinPcap or Ncap.

Next, open a CMD prompt and run:

    C:\>getmac /fo csv /v
    "Connection Name","Network Adapter","Physical Address","Transport Name"
    "Ethernet0","Intel(R) PRO/1000 MT Network Connection","00-0C-29-BB-EC-9B","\Device\Tcpip_{B1B1E59F-FA8F-4A7B-B28C-7A26F6E00F5A}"

Note down the Identifier for your adapter of interest (here: Ethernet0), in this example the identifier is:

    \Device\Tcpip_{B1B1E59F-FA8F-4A7B-B28C-7A26F6E00F5A}

To capture traffic on the interface, 
you must prefix the interface ID ({B1B1E59F-FA8F-4A7B-B28C-7A26F6E00F5A}) with \Device\NPF_

This leaves us with the final command:

    net.exe capture -iface \Device\NPF_{B1B1E59F-FA8F-4A7B-B28C-7A26F6E00F5A}

**Comment by tee2015** [comment]
Ok got it, i will give it a try and once all is good I will close this issue.Thank you for your quick reply and also for this awesome project.

**Comment by tee2015** [comment]
Awesome its now working :) Thank you @dreadl0ck
