### ISSUE TITLE
flag provided but not defined: -encodedCommand

### ISSUE THREAD

**Issue by aygupt1822** [dreadl0ck/ja3#9]
I am getting error, when I am using this ja3 library on windows for live capture analysis
![image](https://user-images.githubusercontent.com/63344523/116542913-e3f6fa80-a8f5-11eb-998c-8298a4ed403c.png)

**Comment by dreadl0ck** [comment]
You seem to be passing a flag that does not exist: -encodedCommand

even though I can't see it in your screenshot.

Btw, put the interface name in string literals, to avoid side effects of the special characters in there for your shell.

**Comment by aygupt1822** [comment]
I guess it be because I am using Windoes Terminal instead of cmd.
Let me try it on cmd and also the interface name in string literals. I will get back to you.

Thanks for your help

**Comment by aygupt1822** [comment]
> You seem to be passing a flag that does not exist: -encodedCommand
> 
> even though I can't see it in your screenshot.
> 
> Btw, put the interface name in string literals, to avoid side effects of the special characters in there for your shell.

Hey I tried with what you said in your solution, but still it is still not working. now I am running the command in cmd, but now I am getting a new error that "Device not found"

![image](https://user-images.githubusercontent.com/63344523/116787150-3fb6b480-aaab-11eb-8b89-71b07f0116b7.png)

**Comment by aygupt1822** [comment]
> You seem to be passing a flag that does not exist: -encodedCommand
> 
> even though I can't see it in your screenshot.
> 
> Btw, put the interface name in string literals, to avoid side effects of the special characters in there for your shell.

Hey I managed to solve the problem. I just replaced \Tcpip to \NPF and it worked !!!!

The command was `go run main.go -iface "\Device\NPF_{0A72D229-0C2D-4F1D-B1B5-ABAEF0D9274A}"`

Thank you for your help !!!!

![image](https://user-images.githubusercontent.com/63344523/116789707-cfaf2b00-aab8-11eb-92d8-7fb39435d523.png)
